# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleAnonymousBoard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('MsgId', models.AutoField(primary_key=True, serialize=False)),
                ('Unixtime', models.BigIntegerField()),
                ('Username', models.CharField(max_length=20)),
                ('MessageString', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
